### ISSUE TITLE
✨ [Feat] 플로우 이미지 추가

### ISSUE THREAD

**Issue by catturtle123** [TeamAvAb/AvAb-Back#131]
## 📝 개요
- 플로우 이미지 추가

## ✔️ To-Do
- [ ] 플로우 생성 시 이미지 추가
- [ ] 플로우 조회 시 이미지 리턴
- [ ] 플로우 상세 조회시 이미지 리턴

## 👀 ETC
- 참고자료 등 기타 내용 작성
